// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRO131.DataContext;

#nullable disable

namespace PRO131.Migrations
{
    [DbContext(typeof(DuAn1Context))]
    [Migration("20250815151417_DuAn_1")]
    partial class DuAn_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PRO131.Models.ChucVu", b =>
                {
                    b.Property<int>("MaCv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCv"));

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaCv")
                        .HasName("PK__ChucVu__27258E76FF785957");

                    b.HasIndex(new[] { "TenChucVu" }, "UQ__ChucVu__A7E2123EAF5212F9")
                        .IsUnique();

                    b.ToTable("ChucVu", (string)null);
                });

            modelBuilder.Entity("PRO131.Models.HangSanXuat", b =>
                {
                    b.Property<int>("MaHangSx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaHangSX");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHangSx"));

                    b.Property<string>("QuocGia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenHangSanXuat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaHangSx")
                        .HasName("PK__HangSanX__8C6D28FE2283B8AB");

                    b.HasIndex(new[] { "TenHangSanXuat" }, "UQ__HangSanX__FC53413B6B59E892")
                        .IsUnique();

                    b.ToTable("HangSanXuat", (string)null);
                });

            modelBuilder.Entity("PRO131.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHd"));

                    b.Property<int>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<int>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<DateOnly>("NgayBan")
                        .HasColumnType("date");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaHd")
                        .HasName("PK__HoaDon__2725A6E0586855FA");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaNv");

                    b.HasIndex(new[] { "NgayBan" }, "IX_HoaDon_NgayBan");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("PRO131.Models.HoaDonChiTiet", b =>
                {
                    b.Property<int>("MaHdct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaHDCT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHdct"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MaHd")
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    b.Property<int>("MaSpct")
                        .HasColumnType("int")
                        .HasColumnName("MaSPCT");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaHdct")
                        .HasName("PK__HoaDonCh__1419C129D1FA11E9");

                    b.HasIndex("MaHd");

                    b.HasIndex("MaSpct");

                    b.ToTable("HoaDonChiTiet", (string)null);
                });

            modelBuilder.Entity("PRO131.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKh"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaKh")
                        .HasName("PK__KhachHan__2725CF1E61085AAD");

                    b.HasIndex(new[] { "SoDienThoai" }, "UQ__KhachHan__0389B7BD36D4066C")
                        .IsUnique()
                        .HasFilter("[SoDienThoai] IS NOT NULL");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("PRO131.Models.KichCo", b =>
                {
                    b.Property<int>("MaSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSize"));

                    b.Property<string>("KichThuoc")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaSize")
                        .HasName("PK__KichCo__A787E7ED651B8863");

                    b.ToTable("KichCo", (string)null);
                });

            modelBuilder.Entity("PRO131.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLoai")
                        .HasName("PK__LoaiSanP__730A57592AA95BF1");

                    b.HasIndex(new[] { "TenLoai" }, "UQ__LoaiSanP__E29B1042CE671788")
                        .IsUnique();

                    b.ToTable("LoaiSanPham", (string)null);
                });

            modelBuilder.Entity("PRO131.Models.MauSac", b =>
                {
                    b.Property<int>("MaMau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMau"));

                    b.Property<string>("TenMau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaMau")
                        .HasName("PK__MauSac__3A5BBB7DDC923CFF");

                    b.ToTable("MauSac", (string)null);
                });

            modelBuilder.Entity("PRO131.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNv"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("MaCv")
                        .HasColumnType("int")
                        .HasColumnName("MaCV");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaNv")
                        .HasName("PK__NhanVien__2725D70A9E4C081B");

                    b.HasIndex("MaCv");

                    b.HasIndex(new[] { "SoDienThoai" }, "UQ__NhanVien__0389B7BDB25EE620")
                        .IsUnique()
                        .HasFilter("[SoDienThoai] IS NOT NULL");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("PRO131.Models.SanPham", b =>
                {
                    b.Property<int>("MaSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSp"));

                    b.Property<int>("MaHangSx")
                        .HasColumnType("int")
                        .HasColumnName("MaHangSX");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaSp")
                        .HasName("PK__SanPham__2725081C16443D9B");

                    b.HasIndex("MaHangSx");

                    b.HasIndex("MaLoai");

                    b.HasIndex(new[] { "TenSanPham" }, "IX_SanPham_Ten");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("PRO131.Models.SanPhamChiTiet", b =>
                {
                    b.Property<int>("MaSpct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaSPCT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSpct"));

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MaMau")
                        .HasColumnType("int");

                    b.Property<int>("MaSize")
                        .HasColumnType("int");

                    b.Property<int>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaSpct")
                        .HasName("PK__SanPhamC__9ED62547551A29C8");

                    b.HasIndex("MaMau");

                    b.HasIndex("MaSize");

                    b.HasIndex("MaSp");

                    b.ToTable("SanPhamChiTiet", (string)null);
                });

            modelBuilder.Entity("PRO131.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTk"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaTk")
                        .HasName("PK__TaiKhoan__27250070984E880E");

                    b.HasIndex("MaNv");

                    b.HasIndex(new[] { "TenDangNhap" }, "UQ__TaiKhoan__55F68FC046B0C3C0")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("PRO131.Models.HoaDon", b =>
                {
                    b.HasOne("PRO131.Models.KhachHang", "MaKhNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKh")
                        .IsRequired()
                        .HasConstraintName("FK__HoaDon__MaKH__656C112C");

                    b.HasOne("PRO131.Models.NhanVien", "MaNvNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__HoaDon__MaNV__6477ECF3");

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("PRO131.Models.HoaDonChiTiet", b =>
                {
                    b.HasOne("PRO131.Models.HoaDon", "MaHdNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("MaHd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__HoaDonChiT__MaHD__6B24EA82");

                    b.HasOne("PRO131.Models.SanPhamChiTiet", "MaSpctNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("MaSpct")
                        .IsRequired()
                        .HasConstraintName("FK__HoaDonChi__MaSPC__6A30C649");

                    b.Navigation("MaHdNavigation");

                    b.Navigation("MaSpctNavigation");
                });

            modelBuilder.Entity("PRO131.Models.NhanVien", b =>
                {
                    b.HasOne("PRO131.Models.ChucVu", "MaCvNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaCv")
                        .IsRequired()
                        .HasConstraintName("FK__NhanVien__MaCV__48CFD27E");

                    b.Navigation("MaCvNavigation");
                });

            modelBuilder.Entity("PRO131.Models.SanPham", b =>
                {
                    b.HasOne("PRO131.Models.HangSanXuat", "MaHangSxNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaHangSx")
                        .IsRequired()
                        .HasConstraintName("FK__SanPham__MaHangS__5629CD9C");

                    b.HasOne("PRO131.Models.LoaiSanPham", "MaLoaiNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaLoai")
                        .IsRequired()
                        .HasConstraintName("FK__SanPham__MaLoai__571DF1D5");

                    b.Navigation("MaHangSxNavigation");

                    b.Navigation("MaLoaiNavigation");
                });

            modelBuilder.Entity("PRO131.Models.SanPhamChiTiet", b =>
                {
                    b.HasOne("PRO131.Models.MauSac", "MaMauNavigation")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("MaMau")
                        .IsRequired()
                        .HasConstraintName("FK__SanPhamCh__MaMau__5FB337D6");

                    b.HasOne("PRO131.Models.KichCo", "MaSizeNavigation")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("MaSize")
                        .IsRequired()
                        .HasConstraintName("FK__SanPhamCh__MaSiz__5EBF139D");

                    b.HasOne("PRO131.Models.SanPham", "MaSpNavigation")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("MaSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__SanPhamChi__MaSP__5DCAEF64");

                    b.Navigation("MaMauNavigation");

                    b.Navigation("MaSizeNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("PRO131.Models.TaiKhoan", b =>
                {
                    b.HasOne("PRO131.Models.NhanVien", "MaNvNavigation")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaNv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TaiKhoan__MaNV__4D94879B");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("PRO131.Models.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("PRO131.Models.HangSanXuat", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("PRO131.Models.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("PRO131.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("PRO131.Models.KichCo", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("PRO131.Models.LoaiSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("PRO131.Models.MauSac", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("PRO131.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("PRO131.Models.SanPham", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("PRO131.Models.SanPhamChiTiet", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });
#pragma warning restore 612, 618
        }
    }
}
